apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetrisgame
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: cont-1
        image: karthik2024nk/tetrisgame:v2
        ports:
        - containerPort: 3000
